services:
  seekarr:
    image: ghcr.io/diybits/seekarr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seekarr
    ports:
      - "9705:9705"
    volumes:
      - seekarr-config:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped

volumes:
  seekarr-config:
    name: seekarr-config